### ISSUE TITLE
Slučaj upotrebe - raspored tehničara

### ISSUE THREAD

**Issue by mkordic** [mkordic/IS_project#1]
Napraviti dijagram sekvenci ili dijagram aktivnosti na osnovu opisa.

Kratak opis: Sistem omogućava upravi da vidi tehničare koji su na raspolaganju, na osnovu čega pravi raspored radnog vremena tehničara.

Akteri: Uprava

Preduslovi: Sistem je aktivan i korisnik je član uprave.

Postuslovi: Raspored je napravljen i vidljiv svim tehničarima.

Osnovni tok:
1) Klikom na sekciju "Raspored" otvara se kalendar sa radnim danima u tom mesecu.
2) Odabirom radnog dana otvara se prozor gde je potrebno uneti ID, ime i prezime, kao i radno vreme tehničara, i hangar u koji je tehnicar rasporedjen.
3) Klikom na polje ID otvara mu se padajući meni sa svim podacima o dostupnim tehničarima u sistemu (ime, prezime, broj dodeljenih radnih sati, maksimalan broj radnih sati, minimalan broj radnih sati).
4) Odabirom ID tehničara, sva polja iz tačke 2) se automatski popunjavaju, osim radnog vremena i hangara koje je potrebno eksplicitno navesti. Prvo se unosi radno vreme, a nakon toga se automatski mu se nude hangari na kojim nema raspoređen određen broj tehničara.
5) Klikom na "Dodaj tehničara" uneti tehničar se raspoređuje za izabrani dan. Broj radnih sati se automatski ažurira za izabranog tehničara.

Alternativni tok
A1) U slučaju da neki tehničar iznenada nije dostupan za neki period, potrebno je izmeniti raspored.

Specijalni zahtevi:
Tehničar se ne može rasporediti ukoliko nije dostupan. Tehničar nije dostupan ukoliko mu je ispunjen maksimalan broj radnih sati za taj mesec ili ako je na odmoru/bolovanju.

**Comment by mkordic** [comment]
Možda treba dodati i hangar u koji je tehničar raspoređen?

**Comment by vicentijevic** [comment]
Slazem se, stavise mozemo da razmisljamo i o tiketima, da se ne vezujemo za hangare, vec da imamo tikete koje dodljujemo tehnicarima.
